version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 741733132160.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=741733132160.dkr.ecr.us-east-1.amazonaws.com/ecsfs_frontend
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      #- docker build -t $REPOSITORY_URI:latest .
      - cd frontend
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing definitions file...
      - printf '[{"name":"ecsfs-fe-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > frontend-task.json
artifacts:
    files: frontend-task.json
